import { AddExpenseFormType } from "../modules/financial-reports/partials/AddExpenseModal";

export const AddFinancialReportForm1Config = [
  {
    label: "Начало смены",
    name: "start_shift",
    required: true,
    type: "number",
  },
  {
    label: "Фиксированный расход",
    name: "fixed_flow",
    required: true,
    type: "text",
  },
  { label: "Подкрепление", name: "refreshment", required: true, type: "text" },
  { label: "Инкасация", name: "collection", required: true, type: "text" },
  { label: "Залог", name: "deposit", required: true, type: "text" },
  { label: "Выкуп", name: "ransom", required: true, type: "text" },
  { label: "Продление", name: "renewal", required: true, type: "text" },
  {
    label: "Вывод из залогов",
    name: "withdraw_pledges",
    required: true,
    type: "text",
  },
  {
    label: "Частичный выкуп",
    name: "partial_redemption",
    required: true,
    type: "text",
  },
  {
    label: "Продажа товаров",
    name: "selling_goods",
    required: true,
    type: "text",
  },
  {
    label: "Доход за проценты",
    name: "interest_income",
    required: true,
    type: "text",
  },
  {
    label: "Доход за товары",
    name: "income_goods",
    required: true,
    type: "text",
  },
  {
    label: "Возврат товаров",
    name: "return_goods",
    required: true,
    type: "text",
  },
  { label: "Товары бу", name: "used_goods", required: true, type: "text" },
  {
    label: "Залоговые билеты/товары",
    name: "deposit_tickets",
    required: true,
    type: "number",
  },
  {
    label: "Залоговые билеты/готов к продаже",
    name: "pledge_tickets",
    required: true,
    type: "text",
  },
  {
    label: "Заёмный капитал инвесторов",
    name: "investor_capital",
    required: true,
    type: "number",
  },
  {
    label: "Заёмный капитал кредит",
    name: "borrowed_capital",
    required: true,
    type: "text",
  },
  {
    label: "Собственный капитал на руках",
    name: "equity",
    required: true,
    type: "number",
    disabled: true,
  },
  {
    label: "Собственный капитал в товарах",
    name: "own_capital",
    required: true,
    type: "number",
    disabled: true,
  },
  {
    label: "Конец смены",
    name: "end_shift",
    required: true,
    type: "number",
    disabled: true,
  },
];

export const AddFinancialReportForm2Config = [
  {
    label: "Начало смены",
    name: "smart_start_shift",
    required: true,
    type: "number",
  },
  {
    label: "Фиксированный расход",
    name: "smart_fixed_flow",
    required: true,
    type: "text",
  },
  {
    label: "Подкрепление",
    name: "smart_refreshment",
    required: true,
    type: "text",
  },
  {
    label: "Инкасация",
    name: "smart_collection",
    required: true,
    type: "text",
  },
  { label: "Залог", name: "smart_deposit", required: true, type: "text" },
  { label: "Выкуп", name: "smart_ransom", required: true, type: "text" },
  { label: "Продление", name: "smart_renewal", required: true, type: "text" },
  {
    label: "Вывод из залогов",
    name: "smart_withdraw_pledges",
    required: true,
    type: "text",
  },
  {
    label: "Частичный выкуп",
    name: "smart_partial_redemption",
    required: true,
    type: "text",
  },
  {
    label: "Продажа товаров",
    name: "smart_selling_goods",
    required: true,
    type: "text",
  },
  {
    label: "Доход за проценты",
    name: "smart_interest_income",
    required: true,
    type: "text",
  },
  {
    label: "Доход за товары",
    name: "smart_income_goods",
    required: true,
    type: "text",
  },
  {
    label: "Возврат товаров",
    name: "smart_return_goods",
    required: true,
    type: "text",
  },
  {
    label: "Товары бу",
    name: "smart_used_goods",
    required: true,
    type: "text",
  },
  {
    label: "Залоговые билеты/товары",
    name: "smart_deposit_tickets",
    required: true,
    type: "number",
  },
  {
    label: "Залоговые билеты/готов к продаже",
    name: "smart_pledge_tickets",
    required: true,
    type: "text",
  },
  {
    label: "Заёмный капитал инвесторов",
    name: "smart_investor_capital",
    required: true,
    type: "number",
  },
  {
    label: "Заёмный капитал кредит",
    name: "smart_borrowed_capital",
    required: true,
    type: "text",
  },
  {
    label: "Собственный капитал на руках",
    name: "smart_equity",
    required: true,
    type: "number",
    disabled: true
  },
  {
    label: "Собственный капитал в товарах",
    name: "smart_own_capital",
    required: true,
    type: "number",
    disabled: true
  },
  {
    label: "Скупка",
    name: "smart_buying_up",
    required: true,
    type: "number",
  },
  {
    label: "Конец смены",
    name: "smart_end_shift",
    required: true,
    type: "number",
    disabled: true
  },
];

export const initialFormState = {
  start_shift: "",
  fixed_flow: "",
  refreshment: "",
  collection: "",
  deposit: "",
  ransom: "",
  renewal: "",
  withdraw_pledges: "",
  partial_redemption: "",
  selling_goods: "",
  interest_income: "",
  income_goods: "",
  return_goods: "",
  deposit_tickets: "",
  pledge_tickets: "",
  investor_capital: "",
  borrowed_capital: "",
  used_goods: "",
  equity: "",
  own_capital: "",
  express_consumptions: [] as AddExpenseFormType[],
  end_shift: "",
  smart_start_shift: "",
  smart_fixed_flow: "",
  smart_refreshment: "",
  smart_collection: "",
  smart_deposit: "",
  smart_ransom: "",
  smart_renewal: "",
  smart_withdraw_pledges: "",
  smart_partial_redemption: "",
  smart_selling_goods: "",
  smart_interest_income: "",
  smart_income_goods: "",
  smart_return_goods: "",
  smart_deposit_tickets: "",
  smart_pledge_tickets: "",
  smart_investor_capital: "",
  smart_borrowed_capital: "",
  smart_used_goods: "",
  smart_equity: "",
  smart_own_capital: "",
  smart_consumptions: [] as AddExpenseFormType[],
  smart_end_shift: "",
  smart_buying_up: 0,
};
